---
- name: Zabbix Event Rulebook

  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Restart Spooler

      condition: true

      action:
        run_workflow_template:
          name: spooler_recovery_workflow
