---
- name: Zabbix Event Rulebook

  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Restart Spooler

      condition: >
  event.payload.trigger_name ==
  'Windows: "Spooler" (Print Spooler) is not running (startup type automatic)'
  and
  event.payload.event_value == 1

      action:
        run_job_template:
          name: start_spooler
          organization: Default
